apiVersion: v1
kind: Secret
metadata:
  name: spinnaker-service-account-token
  namespace: spinnaker
  annotations:
    kubernetes.io/service-account.name: spinnaker-service-account
type: kubernetes.io/service-account-token

#copy the token from the secret json file for kubecl get secret spinnaker-service-account-token -n spinnaker -o json
#do a base64 --decode paste it into the servicesccount.sh file.