apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spinnaker-ingress
  annotations:
    kubernetes.io/ingress.class: "misc-nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  namespace: spinnaker
spec:
  # tls:
  # - hosts:
  #   - spinnaker.use1-poc-gke.srv.media.net
  #   - spinnaker-api.use1-poc-gke.srv.media.net
  #   secretName: star-srv-media-net-26-12-2023
  rules:
  - host: spinnaker.use1-poc-gke.srv.media.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: spin-deck
            port:
              number: 9000
  - host: spinnaker-api.use1-poc-gke.srv.media.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: spin-gate
            port:
              number: 8084

