apiVersion: apps/v1
kind: Deployment
metadata:
  name: "2048-deployment"
spec:
  selector:
    matchLabels:
      app: "2048"
  replicas: 2
  template:
    metadata:
      labels:
        app: "2048"
    spec:
      imagePullSecrets:
        - name: ar-json-key
      containers:
        - image: us-docker.pkg.dev/cm-java-300806/cmjava-artifact-repo/apps/test:2048
          imagePullPolicy: Always
          name: "2048"
          ports:
            - containerPort: 80
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: service-2048
  labels:
    app: servicelabel
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    app: "2048"
